language: python
install: pip install pyyaml
script:
  - $SCRIPT
after_success:
  - ./tools/scripts/deploy.sh
env:
  - SCRIPT=./tools/scripts/ci_build.sh
  - SCRIPT=./tools/generation/test/run.py
  - SCRIPT=./tools/scripts/ci_lint.sh
