language: python
install: pip install --requirement tools/generation/requirements.txt
script:
  - echo The test generation tool should be working.
  - ./tools/generation/test/run.py
  - sh ./tools/scripts/ci.sh
after_success:
  - sh ./tools/scripts/deploy.sh
